### ISSUE TITLE
업데이트 이후 일부 데미지가 비 정상적으로 집계됨

### ISSUE THREAD

**Issue by Nizika569** [Jay13Jeong/GBFR-logs-anti-cheat#10]
![12345](https://github.com/Jay13Jeong/GBFR-logs-anti-cheat/assets/173801954/c2394c51-6ba2-48e8-86af-a657a24ca951)

**Comment by Jay13Jeong** [comment]
@Nizika569
[1.6.1 여기서도](https://github.com/false-spring/gbfr-logs/releases) 비정상적으로 집계되나요?
오늘 1.3.2 업데이트 때문에 어제 진했했던 체크포인트를 다시 확인해야 할 것 같습니다... :joy:

**Comment by Nizika569** [comment]
현재 사용버전은 0.161.1입니다.
@Jay13Jeong

**Comment by Nizika569** [comment]
![456](https://github.com/Jay13Jeong/GBFR-logs-anti-cheat/assets/173801954/efa8e382-5469-4d4d-a477-958a917f077d)

일반루시시퍼에서 산달폰이 치터로 감지됩니다.

**Comment by Jay13Jeong** [comment]
@Nizika569 
아니요, 감지 기능이 있는 버전 말고 없는 버전이요.
jay13jeong의 "0.161.1"이 아니라  false-spring의 "1.6.1"입니다.

**Comment by Nizika569** [comment]
문제 없습니다.
![4567](https://github.com/Jay13Jeong/GBFR-logs-anti-cheat/assets/173801954/57ea0c3a-65bb-4ae9-bbb8-a56fe2004687)

**Comment by Jay13Jeong** [comment]
@Nizika569 
아니에요 문제가 있네요. 통상 공격이 67만이 기록되어 있습니다.
대미지를 기록하는 DPS 기능에 문제가 있는 것 같습니다.
제가 만든 프로그램은 false-spring님의 DPS 기능을 기반으로 개발되었습니다.
저의 프로그램은 DPS 내역을 가지고 부정행위를 판별합니다.
DPS 기능에 대한 문제를 여기로 [false-spring](https://github.com/false-spring/gbfr-logs/issues) 제보하고 패치가 되기를 기다려야합니다.

그리고 추가 질문으로, 혹시 리링크가 설치된 디스크는 HDD인가요? SSD인가요?

**Comment by Nizika569** [comment]
HDD입니다

**Comment by Jay13Jeong** [comment]
@Nizika569 
어쩌면 SSD 또는 m.2를 구매하셔서 리링크와 감지 프로그램을 설치하면 해결 될 수도 있습니다.

**Comment by Nizika569** [comment]
이미 M.2 SSD 있으니까 거기설치해서 테스트 해보겠습니다

**Comment by Nizika569** [comment]
동일한 문제가 발생합니다. 좀 더 쉽게 구분할수있도록 치팅부분에 붉은색으로 표시되게 해줄수 있는지 궁금합니다.
눈으로 보면서 구분해야할 것 같아요

**Comment by Jay13Jeong** [comment]
@Nizika569 
해당 기능은 시간이 좀 필요해서, 여유가 생기면 추가하겠습니다.
본업 때문에 현재는 어렵습니다.
