### ISSUE TITLE
Super Ultimate Perfect Dodge triggers cheating

### ISSUE THREAD

**Issue by K3N-GBFR** [Jay13Jeong/GBFR-logs-anti-cheat#6]
New sigil Super Ultimate Perfect Dodge increased 50% dmg cap is giving the cheating notice

![kO7dWmT](https://github.com/Jay13Jeong/GBFR-logs-anti-cheat/assets/172115856/39216297-f61b-42f0-b62e-885eaabdc9ee)
![uRyDMJP](https://github.com/Jay13Jeong/GBFR-logs-anti-cheat/assets/172115856/59331c07-050a-4de7-b126-c8829331f4a7)

**Comment by Jay13Jeong** [comment]
@K3N-GBFR  
Thank you for bringing this to our attention. I will test it with the [pre-release](https://github.com/Jay13Jeong/GBFR-logs-anti-cheat/releases) version and upload the final version after testing. I appreciate your feedback!
