### ISSUE TITLE
각성진 + 링크어택시 데미지 치트로 감지됨

### ISSUE THREAD

**Issue by Nizika569** [Jay13Jeong/GBFR-logs-anti-cheat#8]
![cheat](https://github.com/Jay13Jeong/GBFR-logs-anti-cheat/assets/173801954/c1de5070-0651-4ddf-9198-24328ac4d8b6)

각성진 및 링크어택시 상한증가 또는 어떠한 이유로 인해 치트로 감지됨 (가끔 감지되지 않을때가 있음)

**Comment by Jay13Jeong** [comment]
@Nizika569 
제보감사합니다. 의심되는 부분 수정해서 [0.141.9 업로드](https://github.com/Jay13Jeong/GBFR-logs-anti-cheat/releases)했습니다.
