### ISSUE TITLE
업데이트 이후에도 데미지 치트로 감지됨

### ISSUE THREAD

**Issue by Nizika569** [Jay13Jeong/GBFR-logs-anti-cheat#9]
![cheat](https://github.com/Jay13Jeong/GBFR-logs-anti-cheat/assets/173801954/ac4c58cc-40e1-4979-89d5-6c3f2ad0740e)

![cheat2](https://github.com/Jay13Jeong/GBFR-logs-anti-cheat/assets/173801954/530931bb-c145-4ac9-bdf8-053eb0f1f590)

알렉이후 회피행동으로 인해 일어났나 생각했는데 그건 아닌듯함

**Comment by Jay13Jeong** [comment]
@Nizika569 
안녕하세요. 빠른 피드백 감사합니다!
평타 히트 당 max댐이 1800만이 기록되어있는데 칼리는 슈얼닷이 터져도 9만대로 알고 있습니다.
equipment탭의 장비 정보를 캡쳐해 주실 수 있을까요?
그리고 괜찮으시면 본인이 사용 중인 운영체제OS와 CPU정보도 알 수 있을까요?

**Comment by Jay13Jeong** [comment]
@Nizika569 
첨부 감사합니다.  혹시 시간 나실 때 [여기서 1.6.0버전](https://github.com/false-spring/gbfr-logs/releases) 받으시고 칼리가 백만이 넘는 대미지가 동일하게 기록되는지 확인해 주실 수 있나요?

**Comment by Nizika569** [comment]
![1](https://github.com/Jay13Jeong/GBFR-logs-anti-cheat/assets/173801954/31d8ea3c-4026-4aa6-a90a-81f62ac49b34)
![2](https://github.com/Jay13Jeong/GBFR-logs-anti-cheat/assets/173801954/9d43d4ac-a712-46d2-ae80-e6642cabe74c)

안티치트가 포함되지 않은 버전을 사용하면 값은 항상 정상적으로 표시됩니다.

**Comment by Jay13Jeong** [comment]
@Nizika569 
감사합니다. hook문제 같아서 업데이트한 버전을 [다시 업로드](https://github.com/Jay13Jeong/GBFR-logs-anti-cheat/releases) 했습니다.
다시 한번 테스트 부탁드리겠습니다! :pray:
